backend:
  name: github
  repo: kelmedeve/site-kraftgo
  branch: main
  base_url: https://decap-cms-oauth-provider-ocerto-s011qgi60-kelmedeve.vercel.app

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
