backend:
  name: github
  repo: kelmedeve/site-kraftgo   # seu repositório
  branch: main                   # branch principal
  base_url: https://site-kraftgo.vercel.app

media_folder: "static/images/uploads"   # onde os arquivos vão ser salvos no repo
public_folder: "/images/uploads"        # caminho público para acessar as imagens

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
