backend:
  name: github
  repo: kelmedeve/site-kraftgo   # repositório onde ficam os conteúdos
  branch: main
  base_url: https://decap-cms-oauth-provider-fjwh.vercel.app

media_folder: "static/images/uploads"   # pasta onde os arquivos são salvos
public_folder: "/images/uploads"        # caminho público para acessar os arquivos

collections:
  - name: "home"
    label: "Página Inicial"
    files:
      - file: "docs/admin/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "about"
    label: "Página Sobre"
    files:
      - file: "docs/admin/about.md"
        label: "Sobre"
        name: "about"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "contact"
    label: "Página Contato"
    files:
      - file: "docs/admin/contact.md"
        label: "Contato"
        name: "contact"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
