backend:
  name: github
  repo: kelmedeve/site-kraftgo
  branch: main
  base_url: https://seu-oauth-provider.netlify.app
  auth_endpoint: auth

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "home"
    label: "Página Inicial"
    files:
      - file: "docs/admin/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "about"
    label: "Página Sobre"
    files:
      - file: "docs/admin/about.md"
        label: "Sobre"
        name: "about"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "contact"
    label: "Página Contato"
    files:
      - file: "docs/admin/contact.md"
        label: "Contato"
        name: "contact"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
